# ---------------------------------------------------------------------------- #

# Must first create a Secret named "google-cloud-service-account" in namespace
# "default" with key "key" set to the Google Cloud service account's JSON key.

# Must also set the project ID in the StorageClass below where it says
# <INSERT PROJECT ID HERE>.

# ---------------------------------------------------------------------------- #

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gcs-storage-class
provisioner: gcs-provisioner
parameters:
  projectId: <INSERT PROJECT ID HERE>
  secretName: google-cloud-service-account
  secretNamespace: default
  location: EUROPE-WEST2

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gcs-bucket-pvc
spec:
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ei
  storageClassName: gcs-storage-class

---

# Exec into this pod and check the /bucket directory.

apiVersion: v1
kind: Pod
metadata:
  name: gcs-test-pod
spec:
  terminationGracePeriodSeconds: 0  # ensure that the pod can be deleted quickly
  containers:
    - name: container
      image: ubuntu:20.04
      command: [ sleep, infinity ]  # wait until pod is manually deleted
      volumeMounts:
        - name: bucket
          mountPath: /bucket
  volumes:
    - name: bucket
      persistentVolumeClaim:
        claimName: gcs-bucket-pvc

# ---------------------------------------------------------------------------- #
