# ---------------------------------------------------------------------------- #

[tool.black]

line-length = 80
target-version = [ "py39" ]
exclude = "^/pav/csi/spec/"

# ---------------------------------------------------------------------------- #

[tool.isort]

profile = "black"
line_length = 80
skip_glob = "pav/csi/spec/*"

# ---------------------------------------------------------------------------- #
